name: hello_world_ffi
version: 0.0.1
description: >-
  A simple example of calling C code from Dart and Dart from C with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
